import sqlite3




connection = sqlite3.connect("wydatki.db") # IF THE FILE DOESN'T EXIST YET, SQLITE CREATES IT AUTOMATICALLY
cursor = connection.cursor() # A "CURSOR" IS WHAT LETS US RUN SQL COMMANDS AGAINST THE DATABASE

# CREATE THE TABLE ONLY IF IT DOESN'T ALREADY EXIST
# THIS MEANS YOU CAN RE-RUN THIS SCRIPT SAFELY WITHOUT WIPING YOUR DATA

cursor.execute("""
CREATE TABLE IF NOT EXISTS salda (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TYP TEXT NOT NULL UNIQUE,
    KWOTA REAL NOT NULL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS transakcje (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DATA TEXT NOT NULL,
    TYP TEXT NOT NULL,
    KATEGORIA TEXT NOT NULL,
    MIEJSCE TEXT NOT NULL,
    KWOTA REAL NOT NULL,
    KONTO TEXT NOT NULL DEFAULT 'GŁÓWNE'
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS kilometry_opel (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DATA TEXT NOT NULL,
    PRZEBIEG INTEGER NOT NULL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS kilometry_suzuki (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DATA TEXT NOT NULL,
    PRZEBIEG INTEGER NOT NULL
)
""")

connection.commit() # SAVE (COMMIT) THE CHANGES TO THE FILE
connection.close() # ALWAYS CLOSE THE CONNECTION WHEN YOU'RE DONE
